services:
  gitlab:
    image: gitlab/gitlab-ce:19.2.1-ce.0
    container_name: gitlab
    hostname: localhost
    restart: unless-stopped

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        puma['worker_processes'] = 2
        sidekiq['max_concurrency'] = 9
        prometheus_monitoring['enable'] = false
    ports:
      - "8929:8929"
      - "2224:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: "256m"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8929/-/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10m

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
